-- DELETE FROM SEC_USER WHERE LOGIN_ID in ('ppuser1','ppuser2')
-- DELETE FROM SEC_OAUTH_TOKEN WHERE LOGIN_ID in ('ppuser1','ppuser2')
Insert into SEC_USER (LOGIN_ID,PASSWORD,
FULL_NAME,IS_ACTIVE,OFFICE_ID,DEPT_ID,ORG_ID,POLICY_ID,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,EMAIL_ADDRESS_TEMP,
APP_ID,DATE_OF_BIRTH,MOBILE_NO,IS_DELETED,IS_LOGGED_IN,PWD_RETRY_COUNT,
STATUS_UPDATED_ON,PWD_UPDATED_ON,RESET_PASSWORD,PHOTOGRAPH, HOME_PAGE)

Select 'ppuser1','Vlo4NI7LmJNREp0AUp1aevEeD8fss0GwW5temIi9a0zubM6vgylwxAsTgKxlO6TaWRhQRSzIZfMAXAy3nHWN1Q==',
'Prepaid User 1 - Vision Web',1,'1',1,'1','admin-policy',GetDate(), 'RX-SYSTEM', GetDate(), 'RX-SYSTEM', 'muhammad.raza@avanzasolutions.com',
'backoffice',GetDate(),'022300122233',0,0,0,GetDate(),GetDate(),0,'default-user.jpeg','prepaidcard.dailyoperation' Union ALL

Select 'ppuser2','brPu1gB3SkvBVxpqqMBi43JsJgHdw+1dXV0bNOM/Uk1j1Qtxgf3zEKmUBdUdCYkcotGO84gVdWCJYE4JiY9/kA==',
'Prepaid User 2 - Vision Web',1,'1',1,'1','admin-policy',GetDate(), 'RX-SYSTEM', GetDate(), 'RX-SYSTEM', 'muhammad.raza@avanzasolutions.com',
'backoffice',GetDate(),'022300122233',0,0,0,GetDate(),GetDate(),0,'default-user.jpeg','prepaidcard.dailyoperation';




--- DELETE FROM SEC_GROUP WHERE GROUP_ID in ('prepaid','prepaid')
Insert into SEC_GROUP (GROUP_ID,GROUP_NAME,APP_ID,HOME_PAGE,IS_ACTIVE,IS_ADMIN,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY) 
Select 'prepaid','Prepaid - Vision Web','backoffice','prepaidcard.dailyoperation',1,1,GetDate(),'RX-SYSTEM',GetDate(),'RX-SYSTEM';



--- DELETE FROM SEC_USER_GROUP WHERE LOGIN_ID in ('ppuser1','ppuser2')
Insert into SEC_USER_GROUP (GROUP_ID,LOGIN_ID,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY) 
Select 'prepaid','ppuser1',GetDate(),'RX-SYSTEM',GetDate(),'RX-SYSTEM' Union All
Select 'prepaid','ppuser2',GetDate(),'RX-SYSTEM',GetDate(),'RX-SYSTEM';



--- DELETE FROM SEC_USER_BRANCH WHERE LOGIN_ID in ('ppuser1','ppuser2')
Insert into SEC_USER_BRANCH(BRANCH_CODE,LOGIN_ID,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY)
Select '0','ppuser1',GetDate(),'RX-SYSTEM',GetDate(),'RX-SYSTEM' Union All
Select '0','ppuser2',GetDate(),'RX-SYSTEM',GetDate(),'RX-SYSTEM';


--- DELETE FROM SEC_USER_ENTITY WHERE LOGIN_ID in ('ppuser1','ppuser2')
Insert into SEC_USER_ENTITY(ENTITY_ID,LOGIN_ID,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY)
Select 1,'ppuser1',GetDate(),'RX-SYSTEM',GetDate(),'RX-SYSTEM' Union All
Select 1,'ppuser2',GetDate(),'RX-SYSTEM',GetDate(),'RX-SYSTEM';




-- SELECT * FROM SEC_GROUP_PERMISSION WHERE GROUP_ID='prepaid'
/* DELETE FROM SEC_GROUP_PERMISSION WHERE GROUP_ID='prepaid' */
/*
Insert into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,CAN_UPDATE,CAN_DELETE,IS_AUDITING_ALLOWED,SEQUENCE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY) 
Select 'prepaid',PERMISSION_ID,CAN_CREATE,CAN_UPDATE,CAN_DELETE,IS_AUDITING_ALLOWED,4,GetDate(),'RX-SYSTEM',GetDate(),'RX-SYSTEM'
From SEC_PERMISSION with (nolock);
*/
-- PERMISSION ONLY FOR "PREPAID CARDS" & "MULTI CURRENCY" MODULES
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','prepaidcard.cardlink',0,0,1,0,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,2);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','prepaidcard.prepaidimport',1,0,1,1,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,11);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','prepaidcard',0,0,0,0,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,3);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','prepaidcard.enrollment',1,0,1,0,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,12);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','prepaidcard.dailyoperation',0,0,1,0,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,12);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','prepaidcard.dailyoperation.recharge',0,0,1,0,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,12);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','prepaidcard.dailyoperation.close',0,0,1,0,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,12);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','prepaidcard.manual',0,0,1,0,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,12);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','prepaidcard.reversal',0,0,1,0,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,12);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','cardproduction.cardoperations.isMakerChecker',1,0,1,1,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,null);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','prepaidcard.balanceimport',0,0,1,0,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,12);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','prepaidcard.balanceimport.checker',0,0,1,0,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,12);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','prepaidcard.balanceimport.maker',0,0,1,0,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,12);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','prepaidcard.balanceimport.import',0,0,1,0,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,12);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','cardproduction',0,0,0,0,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,3);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','cardproduction.newcardrequest',1,0,1,1,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,1);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','cardproduction.newcardrequest.checker',0,0,0,0,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,null);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','cardproduction.newcardrequest.maker',0,0,0,0,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,null);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','cardproduction.cardgeneration',0,0,1,1,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,2);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','cardproduction.cardgeneration.maker',0,0,0,0,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,1);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','cardproduction.cardgeneration.export',1,0,1,1,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,7);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','cardproduction.cardoperations',1,0,1,1,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,7);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','cardproduction.cardoperations.changecardtype',1,0,1,1,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,null);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','cardproduction.cardoperations.markas',1,0,1,1,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,null);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','cardproduction.cardoperations.renewexpiredcard',1,0,1,1,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,null);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','cardproduction.cardoperations.replacement',1,0,1,1,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,null);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','cardproduction.cardoperations.supplementary',1,0,1,1,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,null);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','cardproduction.bulkcardgeneration',1,0,1,1,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,9);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','cardproduction.bulkcardgeneration.cardrequest',1,0,1,1,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,1);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','cardproduction.prepaidimport',1,0,1,1,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,11);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','cardproduction.personalizedcardrequest',1,0,1,1,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,12);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','cardproduction.personalizedcardrequest.maker',1,0,1,1,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,12);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','cardproduction.personalizedcardrequest.checker',1,0,1,1,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,12);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','reports',0,0,0,0,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,7);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','reports.backoffice.activity',0,0,0,0,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,null);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','reports.backoffice.activity.grouppermission',0,0,0,0,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,null);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','reports.backoffice.activity.makerchecker',0,0,0,0,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,null);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','reports.backoffice.activity.useraudit',0,0,0,0,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,null);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','reports.backoffice.activity.userauditdetail',0,0,0,0,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,null);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','reports.backoffice.activity.groupuser-branch',0,0,0,0,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,null);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','reports.backoffice.activity.groupuser-list',0,0,0,0,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,null);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','reports.backoffice.activity.usersession',0,0,0,0,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,null);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','reports.backoffice.customer',0,0,0,0,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,null);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','reports.backoffice.customer.registeredusers',0,0,0,0,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,null);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','reports.backoffice.customer.useractivity',0,0,0,0,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,null);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','reports.backoffice.customer.usersession',0,0,0,0,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,null);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','reports.backoffice.customer.usersessionkilled',0,0,0,0,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,null);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','reports.backoffice.customer.bannerreport',0,0,0,0,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,null);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','reports.backoffice.transaction',0,0,0,0,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,null);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','reports.backoffice.transaction.transactionlog',0,0,0,0,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,null);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','reports.backoffice.transaction.billpayment',0,0,0,0,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,null);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','reports.backoffice.transaction.channelwisetransactionsummary',0,0,0,0,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,null);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','reports.backoffice.transaction.offlinetransactioncc',0,0,0,0,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,null);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','reports.backoffice.transaction.offlinetransactionft',0,0,0,0,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,null);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','reports.backoffice.transaction.offlinetransactionint',0,0,0,0,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,null);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','reports.backoffice.transaction.offlinetransactionint.trdp',0,0,0,0,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,null);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','view-unmasked',0,0,0,0,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,7);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','view-unmasked-logs',0,0,0,0,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,7);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','view-unmasked-reports',0,0,0,0,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,7);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','cardproduction.prepaidimport.checker',0,0,0,0,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,7);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','checker-bulkcardrequest',0,0,0,0,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,7);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','hk',0,0,0,0,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,5);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','hk.currency',1,0,1,1,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,4);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','hk.product',1,0,1,1,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,1);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','hk.program',1,0,1,1,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,2);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','hk.accounttype',1,0,1,1,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,5);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','security',0,0,0,0,GETDATE(),'admin',GETDATE(),'admin',null,null,null,6);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','security.users',1,0,1,1,GETDATE(),'admin',GETDATE(),'admin',null,null,null,1);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','security.groups',1,0,1,1,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,2);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','hk.regulatoryservice',0,0,0,0,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,null);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','hk.regulatoryservice.bankregulatory',1,0,1,1,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,null);
Insert Into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) values ('prepaid','hk.regulatoryservice.customerregulatory',1,0,1,1,GETDATE(),'SYSTEM',GETDATE(),'SYSTEM',null,null,null,null);






-- Select * From Sec_User Where Login_Id LIKE 'ppuser2%'



-- For unlock user
Update Sec_User	Set Pwd_Retry_Count = 0, Is_Active=1, IS_LOGGED_IN=0, UPDATED_ON=GetDate()
Where LOGIN_ID in ('admin','ppuser1','superuser1')


-- For reset existing password [new pwd: Avanza@1234]
Update Sec_User Set Password = 'QVBNgxg/DyreUIvNz5fBFJD35dTyagIjK3TsaCXpw0YunUjhajjZ2rY/tOrCNIknqiEC+FxVqdG8WRHcflnc8Q==', UPDATED_ON=GetDate()
Where Login_Id = 'ppuser1';


-- For reset existing password [new pwd: Avanza@1234]
Update Sec_User Set Password = '+GY4SjjFrZkZvMld8E71C/Lh4nQtPUvZudRZNmCiUl1uMNUE7PMqIK6HgiybdvYwzwR0TRiGmvt308IjQNmeuQ==', UPDATED_ON=GetDate()
Where Login_Id = 'superuser1';


-- For reset existing password [new pwd: admin]
Update Sec_User Set Password = 'qy51bJJhh7Y6KQCKeQAdJoK/dmx+KzGxw+SHjObwndsj0fFSVxGO2GyytSXqz2apgRqwubkBARkicUKb7lrqLg==', UPDATED_ON=GetDate()
Where Login_Id = 'admin';