
/* Execute on VSN */
Create OR Replace View helper_VW_FIELD_MAPPING AS
	Select 
		N.NETWORK_ID, N.NAME, FL.INTERNAL_FIELD_NAME, MAP.LOG_FIELD_NAME, 
		MAP.MSG_FIELD_ID, MON.MSG_FIELD_ID "LIVEMONITORINGFIELDS"
	From LOG_FIELD_MAPPING MAP
	INNER JOIN INTERNAL_FIELDS FL on MAP.INTERNAL_FIELD_ID = FL.INTERNAL_FIELD_ID
	INNER JOIN NETWORK N on MAP.NETWORK_ID = N.NETWORK_ID
	LEFT JOIN LOG_FIELD_MONITORING MON on (N.NETWORK_ID = MON.NETWORK_ID AND MAP.MSG_FIELD_ID = MON.MSG_FIELD_ID)
	--WHERE N.NETWORK_ID = 7
	-- Order by N.NAME, INTERNAL_FIELD_NAME, LOG_FIELD_NAME
;
/

-- Select * From helper_VW_FIELD_MAPPING Order by NAME, INTERNAL_FIELD_NAME, LOG_FIELD_NAME


Execute DelObject('helper_SP_GET_FIELD_MAPPING', 'PROCEDURE');
Create OR Replace PROCEDURE helper_SP_GET_FIELD_MAPPING(
                                                  l_return    OUT SYS_REFCURSOR)
AS
BEGIN
	OPEN l_return FOR
        Select NETWORK_ID,NAME,INTERNAL_FIELD_NAME,LOG_FIELD_NAME,MSG_FIELD_ID,LIVEMONITORINGFIELDS
        FROM helper_VW_FIELD_MAPPING
        Order by NAME, INTERNAL_FIELD_NAME, LOG_FIELD_NAME;
END;
/

