

CREATE OR REPLACE VIEW helper_VW_Permissions AS
	Select distinct P.PERMISSION_ID, P.PERMISSION_NAME, P.PER_PARENT_ID, P.PERMISSION_TYPE, P.CAN_CREATE, P.CAN_UPDATE, P.CAN_DELETE, P.IS_AUDITING_ALLOWED, P.LOCATION, P.VIEW_NAME,
			Case When NVL(P.PERMISSION_ID, '') = '' Then 'Not Found' Else 'Found' End AS PERMISSION_MAP,
        (     
            Select listagg(G.GROUP_ID,', ') within GROUP(ORDER BY G.PERMISSION_ID)
            FROM (Select distinct PERMISSION_ID,GROUP_ID From SEC_GROUP_PERMISSION) G
            Where G.PERMISSION_ID = P.PER_PARENT_ID
        )  AS "GROUP_PERMISSION"
		
	From SEC_PERMISSION P
	Left Join SEC_APP_PERMISSION_MAP M On P.PERMISSION_ID = M.PERMISSION_ID;
/
