
Create View helper_OPERATION_RECORDS 
As
	SELECT 'ACCOUNT' TableName, COUNT(1) Records FROM ACCOUNT with(nolock) 
	Union All
	SELECT 'CUSTOMER', COUNT(1) FROM CUSTOMER with(nolock) 
	Union All
	SELECT 'CUSTOMER_ACCOUNT', COUNT(1) FROM CUSTOMER_ACCOUNT with(nolock) 
	Union All
	SELECT 'DEBIT_CARD', COUNT(1) FROM DEBIT_CARD with(nolock) 
	Union All
	SELECT 'DEBIT_CARD_ACCOUNT', COUNT(1) FROM DEBIT_CARD_ACCOUNT with(nolock) 
	Union All
	SELECT 'CUSTOMER_CHANNEL_AUTHEN', COUNT(1) FROM CUSTOMER_CHANNEL_AUTHEN with(nolock) 
;
