

IF OBJECT_ID('helper_SP_DELETE_CHECKER', 'P') IS NOT NULL
	Drop PROCEDURE helper_SP_DELETE_CHECKER
GO


CREATE PROCEDURE helper_SP_DELETE_CHECKER as 
BEGIN
SET NOCOUNT ON;
    	
	/*
	SELECT * FROM DATA_CHECKER_MAIN ORDER BY 1 desc
	SELECT * FROM DATA_CHECKER_DETAIL ORDER BY 1 desc
	SELECT * FROM DATA_CHECKER_MAIN ORDER BY 1 desc

	Select * Into CHECKER_MAKER_REQUEST_BK00
	From CHECKER_MAKER_REQUEST

	Select * Into DATA_CHECKER_DETAIL_BK00
	From DATA_CHECKER_DETAIL

	Select * Into DATA_CHECKER_MAIN_BK00
	From DATA_CHECKER_MAIN
	*/

	TRUNCATE TABLE DATA_CHECKER_DETAIL;
	
	TRUNCATE TABLE CHECKER_MAKER_REQUEST;
	
	DELETE FROM DATA_CHECKER_MAIN;
	
END
-- exec helper_SP_DELETE_CHECKER