
CREATE VIEW [dbo].[helper_VW_DATA_CHECKER] AS

	Select 
		M.DATA_CHECKER_MAIN_ID
		,M.TABLE_NAME
		,M.TABLE_ID
		,M.STATUS
		,M.CREATED_ON
		,M.CREATED_BY
		,M.IS_NEW
		,M.PK_COLUMN_NAME
		,SF.TABLE_NAME as 'PARENT CHECKER_MAIN'
		,M.ACTION_MODE
		,M.TABLE_DISPLAY_NAME
		,M.BRANCH_CODE
		,M.ENTITY_ID
		,M.TABLE_FIELD_NAME
		,M.TABLE_FIELD_VALUE
		,M.SHOW_DETAILS as 'MAIN_SHOW_DETAILS'
		,M.TABLE_ID_TEXT
		,M.TABLE_ID_TEXT_COLUMN
		,M.SEQUENCE
		,M.BANK_CODE
		,D.FIELD_NAME
		,D.OLD_TEXT_VALUE
		,D.NEW_VALUE
		,D.NEW_TEXT_VALUE
		,D.SHOW_DETAILS as 'DETAIL_SHOW_DETAILS'
		,D.FIELD_DISPLAY_NAME
		,D.VALUE_TYPE
	From DATA_CHECKER_MAIN M
	Left Join DATA_CHECKER_MAIN SF On M.PARENT_ID = SF.DATA_CHECKER_MAIN_ID
	Left Join DATA_CHECKER_DETAIL D ON M.DATA_CHECKER_MAIN_ID = D.DATA_CHECKER_MAIN_ID
	--ORder by SEQUENCE
	;
GO


  