
IF OBJECT_ID('helper_VW_FIELD_MAPPING', 'V') IS NOT NULL
	Drop View helper_VW_FIELD_MAPPING
GO

/* Execute on VSN */
Create View helper_VW_FIELD_MAPPING AS
	Select 
		N.NETWORK_ID, N.NAME, FL.INTERNAL_FIELD_NAME, MAP.LOG_FIELD_NAME, 
		MAP.MSG_FIELD_ID, MON.MSG_FIELD_ID [LiveMonitoringFields]
	From LOG_FIELD_MAPPING MAP
	INNER JOIN INTERNAL_FIELDS FL on MAP.INTERNAL_FIELD_ID = FL.INTERNAL_FIELD_ID
	INNER JOIN NETWORK N on MAP.NETWORK_ID = N.NETWORK_ID
	LEFT JOIN LOG_FIELD_MONITORING MON on (N.NETWORK_ID = MON.NETWORK_ID AND MAP.MSG_FIELD_ID = MON.MSG_FIELD_ID)
	--WHERE N.NETWORK_ID = 7
	-- Order by N.NAME, INTERNAL_FIELD_NAME, LOG_FIELD_NAME
GO

-- Select * From helper_VW_FIELD_MAPPING Order by NAME, INTERNAL_FIELD_NAME, LOG_FIELD_NAME


IF OBJECT_ID('helper_SP_GET_FIELD_MAPPING', 'P') IS NOT NULL
	Drop PROCEDURE helper_SP_GET_FIELD_MAPPING
GO
CREATE PROCEDURE helper_SP_GET_FIELD_MAPPING as 
BEGIN
	Select *
	FROM helper_VW_FIELD_MAPPING
	Order by NAME, INTERNAL_FIELD_NAME, LOG_FIELD_NAME
END
-- exec helper_SP_GET_FIELD_MAPPING


