

CREATE VIEW helper_VW_Permissions AS
	Select distinct P.PERMISSION_ID, P.PERMISSION_NAME, P.PER_PARENT_ID, P.PERMISSION_TYPE, P.CAN_CREATE, P.CAN_UPDATE, P.CAN_DELETE, P.IS_AUDITING_ALLOWED, P.LOCATION, P.VIEW_NAME,
		(SELECT SUBSTRING((SELECT ', ' + G.GROUP_ID FROM SEC_GROUP_PERMISSION G WHERE G.PERMISSION_ID = P.PER_PARENT_ID ORDER BY G.GROUP_ID FOR XML PATH('')),2,200000)) AS GROUP_PERMISSION,
		Case When ISNULL(P.PERMISSION_ID, '') = '' Then 'Not Found' Else 'Found' End AS PERMISSION_MAP
	From SEC_PERMISSION P
	Left Join SEC_APP_PERMISSION_MAP M On P.PERMISSION_ID = M.PERMISSION_ID
GO
