

IF OBJECT_ID('helper_SP_DELETE_REPORTS', 'P') IS NOT NULL
	Drop PROCEDURE helper_SP_DELETE_REPORTS
GO


CREATE PROCEDURE helper_SP_DELETE_REPORTS as 
BEGIN
SET NOCOUNT ON;
    	
	DELETE FROM SEC_APP_PERMISSION_MAP
	WHERE PERMISSION_ID like 'report%'
	AND PERMISSION_ID <> 'reports'

	DELETE FROM SEC_GROUP_PERMISSION
	WHERE PERMISSION_ID like 'report%'
	AND PERMISSION_ID <> 'reports'

	DELETE FROM SEC_PERMISSION
	WHERE PERMISSION_ID like 'report%'
	AND PERMISSION_ID <> 'reports'
END
-- exec helper_SP_DELETE_REPORTS




-- Delete & Insert Report Module

DELETE From SEC_APP_PERMISSION_MAP where PERMISSION_ID = 'reports';
DELETE From SEC_GROUP_PERMISSION where PERMISSION_ID = 'reports';
DELETE From SEC_PERMISSION where PERMISSION_ID = 'reports';


Insert into SEC_PERMISSION (PERMISSION_ID,PER_PARENT_ID,PERMISSION_NAME,OTHER_LANG_NAME,PERMISSION_TYPE,CAN_CREATE,CAN_UPDATE,CAN_DELETE,IS_AUDITING_ALLOWED,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,FIELD_TYPE,SEQUENCE,LOCATION,VIEW_NAME,CSS_CLASS_NAME,TABLE_NAME,TRAN_CODE,IS_VISIBLE) 
values ('reports',null,'Reports','Reports','MODULE',0,0,0,1,GetDate(),'SYSTEM',GetDate(),'SYSTEM',null,(Select max(SEQUENCE)+1 From SEC_PERMISSION),'Reports/Reports','Index','fa-file',null,null,1);

Insert into SEC_GROUP_PERMISSION (GROUP_ID,PERMISSION_ID,CAN_CREATE,IS_AUDITING_ALLOWED,CAN_UPDATE,CAN_DELETE,CREATED_ON,CREATED_BY,UPDATED_ON,UPDATED_BY,WINDOWS_UPDATED_BY,WINDOWS_CREATED_BY,MACHINE_NAME,SEQUENCE) 
values ('admin','reports',0,0,0,0,GetDate(),'SYSTEM',GetDate(),'SYSTEM',null,null,null,null);

Insert into SEC_APP_PERMISSION_MAP (PERMISSION_ID,APP_ID,DESCRIPTION,CREATED_ON) values ('reports','backoffice',NULL,GetDate());
-- Delete & Insert Report Module