

IF OBJECT_ID('helper_SP_DELETE_GROUP_WITH_USERS', 'P') IS NOT NULL
	Drop PROCEDURE helper_SP_DELETE_GROUP_WITH_USERS
GO


CREATE PROCEDURE helper_SP_DELETE_GROUP_WITH_USERS(@rGroupName varchar(50)) as 
BEGIN
	SET NOCOUNT ON;


	SELECT LOGIN_ID, GROUP_ID INTO #tmp_SEC_USER_GROUP
	FROM SEC_USER_GROUP WHERE GROUP_ID = @rGroupName;


	-- ##### BRANCH #####
	DELETE 
	-- SELECT *
	FROM SEC_USER_BRANCH 
	WHERE LOGIN_ID in (
		Select LOGIN_ID FROM #tmp_SEC_USER_GROUP WHERE GROUP_ID = @rGroupName
	);

	
	-- ##### ENTITY #####
	DELETE 
	-- SELECT *
	FROM SEC_USER_ENTITY 
	WHERE LOGIN_ID in (
		Select LOGIN_ID FROM #tmp_SEC_USER_GROUP WHERE GROUP_ID = @rGroupName
	);

	
	-- ##### TOKEN #####
	DELETE 
	-- SELECT *
	FROM SEC_OAUTH_TOKEN
	WHERE LOGIN_ID in (
		Select LOGIN_ID FROM #tmp_SEC_USER_GROUP WHERE GROUP_ID = @rGroupName
	);

	
	-- ##### USER GROUP #####	
	DELETE 
	-- SELECT *
	FROM SEC_USER_GROUP 
	WHERE LOGIN_ID in (
		Select LOGIN_ID FROM #tmp_SEC_USER_GROUP WHERE GROUP_ID = @rGroupName
	);

	
	-- ##### PWD HISTORY #####
	DELETE 
	-- SELECT *
	FROM SEC_PWD_HISTORY
	WHERE LOGIN_ID in (
		Select LOGIN_ID FROM SEC_USER_GROUP WHERE GROUP_ID = @rGroupName
	);

	
	-- ##### DASHBORAD USER #####
	DELETE 
	-- SELECT *
	FROM DASHBORAD_WIDGETS_MAPPING
	WHERE USER_PAGE_ID in (
		SELECT ID
		FROM DASHBORAD_USER_PAGES
		WHERE LOGIN_ID in (
			Select LOGIN_ID FROM SEC_USER_GROUP WHERE GROUP_ID = @rGroupName
		)
	);

	DELETE 
	-- SELECT *
	FROM DASHBORAD_USER_PAGES
	WHERE LOGIN_ID in (
		Select LOGIN_ID FROM SEC_USER_GROUP WHERE GROUP_ID = @rGroupName
	);

	
	-- ##### USER #####
	DELETE 
	-- SELECT *
	FROM SEC_USER
	WHERE LOGIN_ID in (
		Select LOGIN_ID FROM #tmp_SEC_USER_GROUP WHERE GROUP_ID = @rGroupName
	);

	
	-- ##### GROUP PERMISSION #####
	DELETE 
	-- SELECT *
	FROM SEC_GROUP_PERMISSION 
	WHERE GROUP_ID = @rGroupName;

	
	-- ##### GROUP #####
	DELETE 
	-- SELECT *
	FROM SEC_GROUP 
	WHERE GROUP_ID = @rGroupName;
	
END
-- exec helper_SP_DELETE_GROUP_WITH_USERS

