
 
-- :::.. USER_TABLE ..:::
CREATE OR REPLACE VIEW helper_VW_GET_TABLES AS	
	SELECT
        SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA') "TABLE_SCHEMA",
        C.TABLE_NAME,
        C.COLUMN_NAME,
        C.COLUMN_ID "ORDINAL_POSITION",
        C.DATA_DEFAULT "COLUMN_DEFAULT",
        C.NULLABLE "IS_NULLABLE",
        C.DATA_TYPE,
        C.DATA_LENGTH "CHARACTER_MAXIMUM_LENGTH",
        C.DATA_PRECISION "NUMERIC_PRECISION",
        C.DATA_SCALE "NUMERIC_SCALE",    
        C.CHARACTER_SET_NAME || NVL2(C.CHARACTER_SET_NAME, '_', '') || C.CHAR_COL_DECL_LENGTH "CHARACTER_SET_NAME",
        SYS_CONTEXT('USERENV','LANGUAGE') "COLLATION_NAME"
	FROM	USER_TAB_COLS C
	Inner Join USER_OBJECTS O on (C.TABLE_NAME = O.OBJECT_NAME and O.OBJECT_TYPE = 'TABLE')
	-- Order by TABLE_NAME, COLUMN_NAME, ORDINAL_POSITION;
;
/

 
-- :::.. VIEW ..:::
CREATE OR REPLACE VIEW helper_VW_GET_VIEWS AS
	SELECT
        SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA') "TABLE_SCHEMA",
        C.TABLE_NAME,
        C.COLUMN_NAME,
        C.COLUMN_ID "ORDINAL_POSITION",
        C.DATA_DEFAULT "COLUMN_DEFAULT",
        C.NULLABLE "IS_NULLABLE",
        C.DATA_TYPE,
        C.DATA_LENGTH "CHARACTER_MAXIMUM_LENGTH",
        C.DATA_PRECISION "NUMERIC_PRECISION",
        C.DATA_SCALE "NUMERIC_SCALE",    
        C.CHARACTER_SET_NAME || NVL2(C.CHARACTER_SET_NAME, '_', '') || C.CHAR_COL_DECL_LENGTH "CHARACTER_SET_NAME",
        SYS_CONTEXT('USERENV','LANGUAGE') "COLLATION_NAME"
	FROM	USER_TAB_COLS C
	Inner Join USER_OBJECTS O on (C.TABLE_NAME = O.OBJECT_NAME and O.OBJECT_TYPE = 'VIEW')
	-- Order by TABLE_NAME, COLUMN_NAME, ORDINAL_POSITION;
;
/

 
-- :::.. USER_TABLE CONSTRAINTS ..:::
CREATE OR REPLACE VIEW helper_VW_GET_CONSTRAINTS AS
	SELECT	--DB_NAME() [CONSTRAINT_CATALOG],
			
			O.OWNER "CONSTRAINT_SCHEMA",
			O.TABLE_NAME, 
            
			O.CONSTRAINT_NAME,
			O.CONSTRAINT_TYPE "TYPE", 
			CASE
				WHEN O.CONSTRAINT_TYPE = 'C' THEN 'DEFAULT_CONSTRAINT'
				WHEN O.CONSTRAINT_TYPE = 'R' THEN 'REFERENTIAL_INTEGRITY'
				WHEN O.CONSTRAINT_TYPE = 'P' THEN 'PRIMARY_KEY_CONSTRAINT'
				WHEN O.CONSTRAINT_TYPE = 'U' THEN 'UNIQUE_CONSTRAINT'
				ELSE 'N/A'
			END "TYPE_DESC"

	FROM		ALL_CONSTRAINTS O
	WHERE	OWNER = SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA')
	AND		O.CONSTRAINT_TYPE in ('R','U','P','C')
	-- Order by 3, 5 desc, 4;
;
/


/* 
Select distinct type, type_desc From sys.all_objects order by type_desc;
RESULT ::->>
	C 		DEFAULT_CONSTRAINT
	R		REFERENTIAL_INTEGRITY
	P 		PRIMARY_KEY_CONSTRAINT
	U		UNIQUE_CONSTRAINT
*/

 
-- :::.. DATABASE VERSION ..:::
CREATE OR REPLACE VIEW helper_VW_GET_DB_VERSION AS
        
    SELECT 'Oracle Server' "Name", banner "Version"
    FROM v$version WHERE banner LIKE 'Oracle%'

    UNION ALL

    SELECT DISTINCT 'Oracle Client', client_version
    FROM v$session_connect_info
    WHERE sid = sys_context('USERENV', 'SID')

    UNION ALL
    
	SELECT  'Schema', SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA') FROM dual
;
/

 
-- :::.. USER_TABLE KEY COLUMN INDEXES ..:::
CREATE OR REPLACE VIEW helper_VW_GET_COLUMN_INDEXES AS	
	SELECT 
		 SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA') AS "Schema", 
		 ind.TABLE_NAME "TableName",
		 ind.INDEX_NAME "IndexName",
		 ind.COLUMN_NAME "ColumnName",
		 ic.INDEX_TYPE "IndexType",
		 Case ic.UNIQUENESS WHEN 'UNIQUE' THEN 'YES' ELSE 'NO' END "IsUnique",
		 ind.DESCEND "IsDescendingKey",
		 ind.COLUMN_POSITION "KeyOrdinal"
         
	FROM USER_TAB_COLS c
	inner JOIN user_ind_columns ind  ON (c.TABLE_NAME = ind.TABLE_NAME and c.COLUMN_NAME = ind.COLUMN_NAME)
	inner JOIN user_indexes ic  ON  (ind.TABLE_NAME = ic.TABLE_NAME and ind.INDEX_NAME = ic.INDEX_NAME)
	-- ORDER BY ind.TABLE_NAME, ind.COLUMN_NAME, ind.COLUMN_POSITION;
;
/

 
-- :::.. USER_TABLE IDENTITY COLUMNS ..:::
CREATE OR REPLACE VIEW helper_VW_GET_IDENTITY_COLUMNS AS
	SELECT	
		 SYS_CONTEXT('USERENV', 'CURRENT_SCHEMA') AS "Schema", 
		 C.TABLE_NAME "TableName",
		 C.COLUMN_NAME "ColumnName",
		 IND.INDEX_NAME "IndexName",
		 C.GENERATION_TYPE "GenerationType",
		 C.IDENTITY_OPTIONS "IdentityOptions"
	FROM		USER_TAB_IDENTITY_COLS C
	INNER JOIN	USER_IND_COLUMNS IND  ON (C.TABLE_NAME = IND.TABLE_NAME AND C.COLUMN_NAME = IND.COLUMN_NAME)
    -- Order By 1, 2, 3;
;
/
 

/*
	Select * From helper_VW_GET_DB_VERSION ;

	Select * From helper_VW_GET_TABLES  Order by TABLE_NAME, COLUMN_NAME, ORDINAL_POSITION;
	Select * From helper_VW_GET_VIEWS  Order by TABLE_NAME, COLUMN_NAME, ORDINAL_POSITION;

	Select * From helper_VW_GET_CONSTRAINTS  Order by TABLE_NAME, TYPE desc, CONSTRAINT_NAME;
	Select * From helper_VW_GET_COLUMN_INDEXES  ORDER BY "TableName", "IsUnique" Desc, "IndexName", "KeyOrdinal";

	Select * From helper_VW_GET_IDENTITY_COLUMNS    ORDER BY "Schema", "TableName", "ColumnName";
*/
