namespace Avanza.Common.Enums
{
    public enum UserActionType
    {
        ADD=1,
        UPDATE=2,
        DELETE=3,
        SEARCH=4,
        SEARCH_FORCE = 105,
        CARDGENERATIONMAKER_FORCE = 106,
        READ = 5,
        UPLOAD = 6,
        CardCustomers = 100,
        PrepaidCustomers = 101,
        IMPORT = 102,
        PROCESS = 103,
        REJECT = 104,
        CLEAR = 30,
        RESET = 31,
        LINKCARD=7,
        CARDTOPUP=8,
        CARDCLOSE=9,
        CARDREPLACEMENT=10,
        MANUALADJUSTMENT=11,
        APROVEREJECT=12,
        REVERSAL=13,
        CHANGEPASSWORD=14,
        CARDEXPORT=15,
        CARDGENERATIONMAKER=16,
        CARDGENERATIONCHECKER=17,
        CARDREQUESTADD=18,
        CARDREQUESRCHECKERAPROVEORREJECT=19,
        CARDREQUESRSENDFORAPPROVAL=20,
        FORCEPINGENERATION=21,
        PINGENERATION=22,
        PINPRINT=23,
        SIPAUSE = 1,
        SIRESUME = 2,
        //SIDELETE = 3,
        SIINACTIVE = 3,
        SIACTIVE = 4,
    }
}
