# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
  pull_request:
    branches: 'Utilities/**'
    paths:
    - 'ThreadPool.Net2.0/ThreadPoolConsoleApp/**'

jobs:
  build:

    runs-on: windows-latest
    
   # defaults:
   #   run:
   #     working-directory: ThreadPool.Net2.0/ThreadPoolConsoleApp

    steps:
    - uses: actions/checkout@v4

    - run: ls -R
    
    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v1
      #uses: microsoft/setup-msbuild@v2

    - name: Create Build Directory
      run: mkdir _build

    - name: Navigate to Workspace
      run: |
          cd $GITHUB_WORKSPACE
          echo ${{ github.workspace }}
          echo $GITHUB_WORKSPACE
          echo ${{ github.repository }}
          echo $GITHUB_REPOSITORY
      
    - name: Build Solution ThreadPool.Net2.0
      run: |
        msbuild ThreadPoolConsoleApp.sln
        
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: ThreadPoolConsoleAppBundle
        path: "./_build"
        
