# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
  pull_request:
    branches: [ "Utilities" ]
    paths:
    - 'ThreadPool.Net2.0/ThreadPoolConsoleApp/**'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    #- uses: actions/checkout@v2
    
    - name: Setup MSBuild
      #uses: microsoft/setup-msbuild@v1
      uses: microsoft/setup-msbuild@v2
      with:
        vs-version: '14.0'

    - name: Setup NuGet
      #uses: NuGet/setup-nuget@v1.0.2
      uses: nuget/setup-nuget@v2
      with:
        nuget-api-key: ${{ secrets.NuGetAPIKey }}
        nuget-version: latest

    - name: Navigate to Workspace
      run: |
          cd $GITHUB_WORKSPACE
          echo ${{ github.workspace }}
          echo $GITHUB_WORKSPACE
          echo ${{ github.repository }}
          echo $GITHUB_REPOSITORY

    - name: Create Build Directory
      run: mkdir _build
      
    #- name: Restore Packages
    #  run: nuget restore ThreadPoolConsoleApp.sln
          
    #- name: Restore dependencies
    #  run: dotnet restore
      
    - name: Build Solution ThreadPool.Net2.0
    #  run: |
    #    msbuild.exe ThreadPoolConsoleApp.sln /nologo /nr:false /p:DeployOnBuild=true /p:DeployDefaultTarget=WebPublish /p:WebPublishMethod=FileSystem /p:DeleteExistingFiles=True /p:platform="Any CPU" /p:configuration="Release" /p:PublishUrl="../_build"
    #    msbuild.exe ThreadPoolConsoleApp.sln
    #    msbuild.exe xxxxx.cproj /t:Rebuild
    #    msbuild.exe ThreadPoolConsoleApp.sln /p:Configuration="Release" /p:Platform="x86"
    #    msbuild.exe ThreadPoolConsoleApp.sln -target:NotInSlnfolder:Rebuild;
      run: |
        msbuild ThreadPool.Net2.0/ThreadPoolConsoleApp/ThreadPoolConsoleApp/ThreadPoolConsoleApp.csproj -target:NotInSlnfolder:Rebuild;
        
    - name: Upload artifact
      uses: actions/upload-artifact@v1.0.0
      with:
        name: ThreadPoolConsoleAppBundle
        path: "./_build"
        
    #- name: Build ThreadPool.Net2.0
    #  run: dotnet build --no-restore
    
    #- name: Test ThreadPool.Net2.0
    #  run: dotnet test --no-build --verbosity normal
