# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
  pull_request:
    branches: [ "Utilities" ]
    paths:
    - 'ThreadPool.Net2.0/ThreadPoolConsoleApp/**'

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Navigate to Workspace
      run: |
          echo ${{ github.workspace }}
          echo $GITHUB_WORKSPACE
          echo ${{ github.repository }}
          echo $GITHUB_REPOSITORY
          echo ${{ github.workflow.ref }}
          echo $GITHUB_WORKFLOW_REF
          
    
    - name: Restore dependencies
      run: dotnet restore
    
    - name: Build ThreadPool.Net2.0
      run: dotnet build --no-restore
    
    - name: Test ThreadPool.Net2.0
      run: dotnet test --no-build --verbosity normal
